# Generated by Django 4.2.11 on 2024-04-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='no_image.svg', upload_to='recipes'),
        ),
    ]
