# Generated by Django 4.2.11 on 2024-05-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(help_text='Separate ingredients with a comma', max_length=400),
        ),
    ]
