# Generated by Django 4.2.11 on 2024-05-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, help_text='Leave blank, this will be auto-calculated', max_length=20),
        ),
    ]
